[webservers]
web-a ansible_host=10.0.1.19 ansible_user=user
web-b ansible_host=10.0.2.33 ansible_user=user

[bastion_host]
bastion ansible_host=51.250.86.103 ansible_user=user

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
